---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pr-pipeline
spec:
  params:
  - name: repository
    description: the git repo
  - name: branch
    description: branch
 
  workspaces:
  - name: artifacts

  tasks:
  - name: extract-repository-url
    taskRef:
      name: toolchain-extract-value
    params:
     - name: pipeline-debug
      value: $(params.pipeline-debug)
